In [1]:
#Importing the numpy lib
import numpy as np

In [2]:
#Creating a numpy array
np_array = np.array([3,4,2,45,551])

In [4]:
np_array.shape

(5,)

In [14]:
a=np.array([(42,42,5,4,2),(345,3,4,5,2)],dtype=int)
print(a)

[[ 42  42   5   4   2]
 [345   3   4   5   2]]


In [8]:
a.shape

(2, 5)

In [16]:
#Creating a numpy array of zeros
a=np.zeros((5,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
#Creating a numpy array of ones
b=np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [20]:
#Creating a numpy array for particular values
c=np.full((5,6),10)
print(c)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [21]:
#Creating a numpy array for identity Matrix
ab=np.eye(9)
print(ab)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [22]:
#Creating a numpy array for random values
ac=np.random.random((44,33))
print(ac)

[[0.55401542 0.56130644 0.92992134 ... 0.65876249 0.27066683 0.3515773 ]
 [0.88621956 0.98767655 0.9479185  ... 0.99543283 0.20019784 0.8099053 ]
 [0.10977793 0.73233005 0.11062048 ... 0.65218118 0.89997344 0.33659817]
 ...
 [0.62043985 0.00975998 0.18604575 ... 0.87953257 0.46264548 0.76934714]
 [0.75917344 0.49241844 0.93830441 ... 0.59701209 0.44641736 0.57447674]
 [0.11777739 0.01147797 0.09391369 ... 0.0956381  0.6854548  0.77820983]]


In [26]:
#Creating a numpy array for random integers values
ad=np.random.randint(1,1000,(5,5))
print(ad)

[[954  39 508 283 660]
 [423  50 944 609 346]
 [981 639 116 898 223]
 [234 706 773 365 531]
 [243 480 966 582 382]]


In [30]:
#Creating a numpy array of evenly spaced values
ae=np.linspace(10,100,50)
print(ae)

[ 10.          11.83673469  13.67346939  15.51020408  17.34693878
  19.18367347  21.02040816  22.85714286  24.69387755  26.53061224
  28.36734694  30.20408163  32.04081633  33.87755102  35.71428571
  37.55102041  39.3877551   41.2244898   43.06122449  44.89795918
  46.73469388  48.57142857  50.40816327  52.24489796  54.08163265
  55.91836735  57.75510204  59.59183673  61.42857143  63.26530612
  65.10204082  66.93877551  68.7755102   70.6122449   72.44897959
  74.28571429  76.12244898  77.95918367  79.79591837  81.63265306
  83.46938776  85.30612245  87.14285714  88.97959184  90.81632653
  92.65306122  94.48979592  96.32653061  98.16326531 100.        ]


In [32]:
#Creating a numpy array of evenly spaced values by step value
af=np.arange(10,100,5)
print(af)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [33]:
#Converting a list to nparray
ag=[32,434,2,4234,234]
np_array=np.asarray(ag)
print(np_array)
type(np_array)

[  32  434    2 4234  234]


numpy.ndarray

Analysing of numpy array


In [34]:
a=np.random.randint(10,10000,(10,10))
print(a)

[[7265 6785 7462 7301 5861 1385 7500  736  899 2990]
 [6279  569 2596 7542 9197 7877 1684 6637 8073  340]
 [3273  840 4597  665 1811 4793 5848 1869 4066 4320]
 [2328 7534 8085 7811 1912 8502 2048 6001 7394 6700]
 [1688 5208 5504 2282 2622 4030 7445 4576  923 9280]
 [5375 7711 5199 8820 4883 8396 3785 1414 6893 2895]
 [5037 3324  471 1893 6245 4125 7846 9915 6423 1321]
 [4145  394 7492 2266 9854 6716 5460 7907 4534  963]
 [4899 1523  179  551 3205 8653 7893 3209 7815 2029]
 [5789 8900 6763 7481 2130 4462 3350 7800 6452 5008]]


In [35]:
#Array Dimensions
print(a.shape)

(10, 10)


In [36]:
#Array size
print(a.size)

100


In [37]:
#Number of dimensions
print(a.ndim)

2


In [40]:
#Datatype
print(a.dtype)


int64


Some Mathematical operations


In [42]:
a=np.random.randint(10,1000,(10,10))
b=np.random.randint(10,101,(10,10))

In [43]:
print(a)
print(b)

[[575 657 764 327 580 525 926 993 296 539]
 [334 142 260 323 937 206 977 696 296 512]
 [596 354 448 251 388 753 485 484 219 587]
 [534 106 169 641 632 600 932 852 794 179]
 [942 621 375 198 108 274 889 499 839 171]
 [ 82 762  42 547 829 281 253 521  32 926]
 [365 115 565  55  70 171 758 163 235 973]
 [650 720 814 544 209 574 562 508 547 812]
 [578 625 628 514 924 350 361 667 282 544]
 [276 159 299 316 809 596 384 362 169 253]]
[[ 52  69  85  68 100  77  10  50  24  58]
 [ 64  77  62  69  42  59  70  75  48  27]
 [ 59  59  16  54  99  94  15  20  69  49]
 [ 92  95  98  80  51  78  27  70  77  54]
 [ 60  53  40  52  79  31  24  52  14  73]
 [ 79  86  80  58  35  35  68  30  54  64]
 [ 86  25  24  97  24  72  31  18  46  55]
 [ 62  86  72  30  56  33  31  26  38  56]
 [ 48  18  92  17  65  92  23  13  22  20]
 [ 37  61  99  67  54  49  15  27  60  88]]


In [47]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 627  726  849  395  680  602  936 1043  320  597]
 [ 398  219  322  392  979  265 1047  771  344  539]
 [ 655  413  464  305  487  847  500  504  288  636]
 [ 626  201  267  721  683  678  959  922  871  233]
 [1002  674  415  250  187  305  913  551  853  244]
 [ 161  848  122  605  864  316  321  551   86  990]
 [ 451  140  589  152   94  243  789  181  281 1028]
 [ 712  806  886  574  265  607  593  534  585  868]
 [ 626  643  720  531  989  442  384  680  304  564]
 [ 313  220  398  383  863  645  399  389  229  341]]
[[523 588 679 259 480 448 916 943 272 481]
 [270  65 198 254 895 147 907 621 248 485]
 [537 295 432 197 289 659 470 464 150 538]
 [442  11  71 561 581 522 905 782 717 125]
 [882 568 335 146  29 243 865 447 825  98]
 [  3 676 -38 489 794 246 185 491 -22 862]
 [279  90 541 -42  46  99 727 145 189 918]
 [588 634 742 514 153 541 531 482 509 756]
 [530 607 536 497 859 258 338 654 260 524]
 [239  98 200 249 755 547 369 335 109 165]]
[[29900 45333 64940 22236 58000 40425 